package org.jsuns.commerce.view;

//import org.jsuns.commerce.Cl_Varios;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jsuns.commerce.jpa.Banco;
import org.jsuns.swing.XPanel;

public class frm_mov_bancos extends XPanel{

//    Cl_Varios ven = new Cl_Varios();

    /**
     * Creates new form frm_mov_bancos
     */
    public frm_mov_bancos() {
       /* initComponents();
cbx_banco.setStore(Banco.class);
cbx_banco.load();*/
    }

    private void ver_nro_cuenta(int idban) {

      
            ArrayList cuenta = new ArrayList();
     
            String query = "select nro_cuenta from cuenta where idbanco = '" + idban + "' order by idcuenta asc";
       
//            while (rs.next()) {
//                cuenta.add(rs.getString("nro_cuenta"));
//            }
            /*if (cuenta.size() > 0) {
                cbx_cuenta.removeAllItems();
                for (int j = 0; j < cuenta.size(); j++) {
                    cbx_cuenta.addItem(cuenta.get(j));
                }
            } else {
                cbx_cuenta.removeAllItems();
                JOptionPane.showMessageDialog(null, "cuenta no disponible");
                cbx_cuenta.setEnabled(false);
                cbx_banco.requestFocus();
            }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cer = new javax.swing.JButton();
        btn_ini = new javax.swing.JButton();
        cbx_cuenta = new javax.swing.JComboBox();
        txt_fec_fin = new org.jsuns.swing.XDateField();
        txt_fec_ini = new org.jsuns.swing.XDateField();
        cbx_banco = new org.jsuns.swing.XComboBox();

        setTitle("Movimiento por Banco");

        jLabel1.setForeground(new java.awt.Color(212, 2, 2));
        jLabel1.setText("Seleccion de Bancos - Movimientos");

        jLabel2.setForeground(new java.awt.Color(212, 2, 2));
        jLabel2.setText("Banco:");

        jLabel3.setForeground(new java.awt.Color(212, 2, 2));
        jLabel3.setText("Cuenta:");

        jLabel4.setForeground(new java.awt.Color(212, 2, 2));
        jLabel4.setText("Fecha Inicio:");

        jLabel5.setForeground(new java.awt.Color(212, 2, 2));
        jLabel5.setText("Fecha Fin:");

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        btn_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_ini.setText("Iniciar");
        btn_ini.setEnabled(false);
        btn_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniActionPerformed(evt);
            }
        });
        btn_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_iniKeyPressed(evt);
            }
        });

        cbx_cuenta.setEnabled(false);
        cbx_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_cuentaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbx_cuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_banco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fec_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fec_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ini)
                        .addGap(18, 18, 18)))
                .addComponent(btn_cer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbx_banco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_fec_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_fec_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
*/
    private void cbx_cuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_cuentaKeyPressed
    
    }//GEN-LAST:event_cbx_cuentaKeyPressed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        this.close();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void btn_iniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_iniKeyPressed

    }//GEN-LAST:event_btn_iniKeyPressed

    private void btn_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniActionPerformed
        /*Date fec_ini =txt_fec_ini.getDate();
        Date fec_fin =txt_fec_fin.getDate();
        String cuenta = cbx_cuenta.getSelectedItem().toString();
        Map<String, Object> parametros = new HashMap();
        parametros.put("fec_mov", fec_ini);
        parametros.put("fec_ini", fec_fin);
        parametros.put("cuenta", cuenta);
        ven.ver_reporte("rpt_caja_movimiento_bancos", parametros);
        this.close();*/
    }//GEN-LAST:event_btn_iniActionPerformed

/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_ini;
    private org.jsuns.swing.XComboBox cbx_banco;
    private javax.swing.JComboBox cbx_cuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private org.jsuns.swing.XDateField txt_fec_fin;
    private org.jsuns.swing.XDateField txt_fec_ini;
    // End of variables declaration//GEN-END:variables
*/}
