package org.jsuns.commerce.view;

import javax.swing.table.DefaultTableModel;
import org.jsuns.commerce.frm_menu;
import org.jsuns.swing.XPanel;

public class frm_ver_solicitudes extends XPanel{

//    Cl_Varios ven = new Cl_Varios();
    DefaultTableModel mostrar;
    int i;

    public frm_ver_solicitudes() {
        initComponents();
        retrieve();
    }

    private void retrieve() {
        /*String query = "select sol.fec_sol, date_add(sol.fec_sol, INTERVAL sol.plazo DAY) as fec_apro, sol.idsolicitud, "
                + "sol.estado, sol.id_alm_ori, sol.nick, emp.nom_per, sol.id_alm_des, sol.plazo, sol.fec_env from "
                + "solicitud_articulos as sol inner join usuario as usu on sol.nick=usu.nick inner join empleados as emp on "
                + "usu.dni=emp.dni where id_alm_ori = '" + frm_menu.almacen.getIdAlmacen() + "' or id_alm_des = "
                + "'" + frm_menu.almacen.getIdAlmacen() + "' order by fec_apro desc";
        
        query = "select sol.fec_sol, date_add(sol.fec_sol, INTERVAL sol.plazo DAY) as fec_apro, sol.idsolicitud, "
                + "sol.estado, sol.id_alm_ori, sol.nick, emp.nom_per, sol.id_alm_des, sol.plazo, sol.fec_env from "
                + "solicitud_articulos as sol inner join usuario as usu on sol.nick=usu.nick inner join empleados as emp on "
                + "usu.dni=emp.dni where id_alm_ori = '" + frm_menu.almacen.getIdAlmacen() + "' or id_alm_des = "
                + "'" + frm_menu.almacen.getIdAlmacen() + "' order by fec_apro desc";
        
        
            mostrar = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };

            //Establecer como cabezeras el nombre de las colimnas
            mostrar.addColumn("Fec. Ing.");
            mostrar.addColumn("F. Env. Aprox.");
            mostrar.addColumn("Nro");
            mostrar.addColumn("Estado");
            mostrar.addColumn("Alm. Origen");
            mostrar.addColumn("Solicitante");
            mostrar.addColumn("Alm. Destino");
            mostrar.addColumn("Plazo dias");
            mostrar.addColumn("Fec. Env.");

            //Creando las filas para el JTable
//            while (rs.next()) {
//                Object[] fila = new Object[9];
//                fila[0] =rs.getDate("fec_sol");
//                fila[1] =rs.getDate("fec_apro");
//                fila[2] = rs.getObject("idsolicitud");
//                if (rs.getString("estado").equals("0")) {
//                    fila[3] = "PENDIENTE";
//                } else {
//                    fila[3] = "ENVIADO";
//                }
//                fila[4] = ver_nom(rs.getString("id_alm_ori"));
//                fila[5] = rs.getObject("nom_per");
//                fila[6] = ver_nom(rs.getString("id_alm_des"));
//                fila[7] = rs.getObject("plazo");
//                if (rs.getString("fec_env").equals("7000-01-01")) {
//                    fila[8] = "-";
//                } else {
//                    fila[8] = rs.getObject("fec_env");
//                }
//                mostrar.addRow(fila);
//
//            }
            t_requerimiento.setModel(mostrar);
            t_requerimiento.getColumnModel().getColumn(0).setPreferredWidth(80);
            t_requerimiento.getColumnModel().getColumn(1).setPreferredWidth(80);
            t_requerimiento.getColumnModel().getColumn(2).setPreferredWidth(40);
            t_requerimiento.getColumnModel().getColumn(3).setPreferredWidth(80);
            t_requerimiento.getColumnModel().getColumn(4).setPreferredWidth(80);
            t_requerimiento.getColumnModel().getColumn(5).setPreferredWidth(180);
            t_requerimiento.getColumnModel().getColumn(6).setPreferredWidth(80);
            t_requerimiento.getColumnModel().getColumn(7).setPreferredWidth(50);
            t_requerimiento.getColumnModel().getColumn(8).setPreferredWidth(80);
            //ven.centrar_celda(t_requerimiento, 0);
            //ven.centrar_celda(t_requerimiento, 1);
            //ven.centrar_celda(t_requerimiento, 2);
            //ven.centrar_celda(t_requerimiento, 8);
            mostrar.fireTableDataChanged();*/
        }

    private String ver_nom(String idalm) {
        String nomalm = null;
       
          
            String ver_alm = "select nom_alm from almacen where idAlmacen='" + idalm + "'";
          
//            if (rs.next()) {
//                nomalm = rs.getString("nom_alm");
//            }
       
        return nomalm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_requerimiento = new javax.swing.JTable();
        btn_reg = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_imp = new javax.swing.JButton();
        btn_eli = new javax.swing.JButton();

        setTitle("Listar Pedidos");

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));

        t_requerimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fec. Ing.", "Nro.", "Estado", "Alm. Origen.", "Solicitante", "Alm. Destino", "Plazo Dias", "Fec. Envio"
            }
        ));
        t_requerimiento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        t_requerimiento.setAutoscrolls(false);
        t_requerimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_requerimientoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_requerimiento);

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btn_reg.setText("Crear Pedido");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clipboard_text.png"))); // NOI18N
        btn_ver.setText("Ver Ped.");
        btn_ver.setEnabled(false);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_imp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clipboard_text.png"))); // NOI18N
        btn_imp.setText("Imp. Ped.");
        btn_imp.setEnabled(false);

        btn_eli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cross.png"))); // NOI18N
        btn_eli.setText("Eliminar");
        btn_eli.setEnabled(false);
        btn_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_eli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_imp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        frm_reg_solicitud solicitud = new frm_reg_solicitud();
//        solicitud.setAlmacen(frm_menu.almacen);
        //ven.open(solicitud);
        this.close();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        frm_reg_solicitud soli=new frm_reg_solicitud();
        int idsol = Integer.parseInt(t_requerimiento.getValueAt(i, 2).toString());
//        soli.retrieve(idsol);
        //ven.open(soli);
        this.close();
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        this.close();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void t_requerimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_requerimientoMousePressed
       /* i = t_requerimiento.getSelectedRow();
        if (!t_requerimiento.getValueAt(i, 4).toString().equals(frm_menu.almacen.getNombre()) & 
                !t_requerimiento.getValueAt(i, 3).toString().equals("ENVIADO")) {
            btn_ver.setEnabled(true);
        } else {
            btn_ver.setEnabled(false);
        }*/

    }//GEN-LAST:event_t_requerimientoMousePressed

    private void btn_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliActionPerformed
        int idsol = Integer.parseInt(t_requerimiento.getValueAt(i, 0).toString());
        // Eliminando detalle de solicitud.
        try {
            
            String eli_det = "delete * from detalle_solicitud where idsolicitud = '"+idsol+"'";
 
           
            String eli_sol = "delete * from solicitud_articulos where idsolicitud = '"+idsol+"'";
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
        retrieve();
        
        
    }//GEN-LAST:event_btn_eliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_eli;
    private javax.swing.JButton btn_imp;
    private javax.swing.JButton btn_reg;
    private javax.swing.JButton btn_ver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_requerimiento;
    // End of variables declaration//GEN-END:variables
}
